### ISSUE TITLE
package.json - Remove unnecessary dependencies

### ISSUE THREAD

**Issue by ShaharGrauman** [ShaharGrauman/weka-ojt-filesystem#159]
If we use Bootstrap - do we need:
1- "@emotion/react": "^11.11.3" ?
2- "@emotion/styled": "^11.11.0" ?
3- "@mui/material": "^5.15.7" ?
4- "styled-components": "^6.1.8" ?

If we don't need those - Remove unnecessary dependencies by **uninstall them**

**Comment by ShaharGrauman** [comment]
Remove unnecessary dependencies

**Comment by Hamadabosbet** [comment]
Remove unnecessary dependencies
